---
- name: Ensure munin-node is installed because it includes munin-async (Suse and derivatives).
  community.general.zypper: name=munin-node state=present

- name: Create munin-async user on Suse. Use a fake password so the account is not locked and we can ssh login.
  user:
    name: "{{ munin_async_user }}"
    system: true
    home: "{{ munin_async_home }}"
    password: "$6$fakepassword"

- name: Copy munin-async systemd unit.
  copy:
    src: munin-async/munin-async.service
    dest: "{{ munin_asyncd_initscript }}"

- name: mkdir -p /var/lib/spool/munin
  file:
    path: "/var/lib/spool/munin"
    state: directory
    recurse: true
    mode: 0755
    owner: "{{ munin_async_user }}"
    group: "{{ munin_async_user }}"
